name: mix test

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches:
      - main
      - dev/*
  pull_request:
    branches:
      - main

jobs:
  # Refactoring duplicated yaml is currently not possible
  # because Github does not support anchor syntax (& and *) now.
  mix_test:
    runs-on: ubuntu-latest
    name: mix test
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: jechol
      - name: Install languages
        run: |
          nix-env -i -f shell.nix -A buildInputs &&
          mix local.rebar --force &&
          mix local.hex --force
      - run: mix deps.get
      - run: mix test
